name: Deploy to Azure

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploy to PROD"
            az containerapp update \
              --name spring-petclinic-app \
              --resource-group rg-spring-petclinic \
              --image ghcr.io/shimoyama-y/spring-petclinic:latest
          else
            echo "Deploy to DEV"
            az containerapp update \
              --name spring-petclinic-dev \
              --resource-group rg-spring-petclinic \
              --image ghcr.io/shimoyama-y/spring-petclinic:latest
          fi
